language: ruby

notifications:
  email: false

rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - rbx-19mode
  - 1.8.7
  - ree

matrix:
  allow_failures:
    - rvm: rbx-19mode
    - rvm: ruby-head
    - rvm: 1.8.7
    - rvm: ree

script:
  - "bundle exec rake spec"

